DOMAINS = {
    "Artificial Intelligence and Machine Learning": [
        "Deep Learning",
        "Convolutional Neural Networks",
        "Recurrent Neural Networks",
        "Natural Language Processing",
        "Generative Adversarial Networks",
        "Reinforcement Learning",
        "Supervised Learning",
        "Unsupervised Learning",
        "Transfer Learning",
        "Meta Learning",
        "Explainable AI",
        "Probabilistic Models",
        "Decision Trees",
        "Random Forests",
        "Support Vector Machines"
    ],
    "Human-Computer Interaction": [
        "Brain-Computer Interfaces",
        "User Experience Design",
        "User Interface Design",
        "Augmented Reality",
        "Virtual Reality",
        "Mixed Reality",
        "Interaction Design",
        "Usability Testing",
        "Accessibility",
        "Ergonomics",
        "Emotion Recognition",
        "Multimodal Interfaces",
        "Gesture Recognition"
    ],
    "Big Data and Data Analytics": [
        "Data Mining",
        "Data Visualization",
        "Data Processing Systems",
        "Time Series Analysis",
        "Predictive Analytics",
        "Statistical Analysis",
        "Business Intelligence",
        "Machine Learning for Big Data",
        "Distributed Data Storage",
        "Stream Processing",
        "Data Warehousing",
        "Graph Analytics",
        "Real-time Analytics"
    ],
    "Cybersecurity": [
        "Encryption Algorithms",
        "Secure Software Development",
        "Network Security",
        "Authentication Systems",
        "Digital Forensics",
        "Intrusion Detection Systems",
        "Malware Analysis",
        "Risk Management",
        "Incident Response",
        "Vulnerability Assessment",
        "Security Auditing",
        "Penetration Testing",
        "Blockchain Security",
        "Cloud Security"
    ],
    "Networks and Distributed Systems": [
        "5G and Next Generation Networks",
        "Cloud Computing",
        "Edge Computing",
        "Blockchain Technology",
        "Decentralized Systems",
        "Peer-to-Peer Networks",
        "Network Protocols",
        "Software-Defined Networking",
        "Virtualization Technologies",
        "Distributed Ledger Technology",
        "Scalability and Performance",
        "Network Optimization"
    ],
    "Software Engineering and Development": [
        "Agile Methodologies",
        "DevOps",
        "Microservices Architecture",
        "Software Testing",
        "Continuous Integration/Continuous Deployment",
        "Code Quality and Analysis",
        "Static and Dynamic Analysis",
        "Refactoring Techniques",
        "Software Maintenance",
        "Design Patterns",
        "User-Centered Design"
    ],
    "Robotics and Autonomous Systems": [
        "Robot Kinematics",
        "Path Planning",
        "Sensor Fusion",
        "Autonomous Navigation",
        "Humanoid Robotics",
        "Control Systems",
        "Industrial Robotics",
        "Swarm Robotics",
        "Machine Vision in Robotics"
    ]
}
